// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Protos/Common.proto</summary>
public static partial class CommonReflection {

  #region Descriptor
  /// <summary>File descriptor for Protos/Common.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CommonReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNQcm90b3MvQ29tbW9uLnByb3RvGh9nb29nbGUvcHJvdG9idWYvdGltZXN0",
          "YW1wLnByb3RvIkYKCEN1c3RvbWVyEgwKBE5hbWUYASABKAkSDAoEQ2l0eRgC",
          "IAEoCRIOCgZWaXNpdHMYAyABKAUSDgoGU2FsYXJ5GAQgASgBYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Customer), global::Customer.Parser, new[]{ "Name", "City", "Visits", "Salary" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Customer : pb::IMessage<Customer>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Customer> _parser = new pb::MessageParser<Customer>(() => new Customer());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Customer> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommonReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Customer() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Customer(Customer other) : this() {
    name_ = other.name_;
    city_ = other.city_;
    visits_ = other.visits_;
    salary_ = other.salary_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Customer Clone() {
    return new Customer(this);
  }

  /// <summary>Field number for the "Name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "City" field.</summary>
  public const int CityFieldNumber = 2;
  private string city_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string City {
    get { return city_; }
    set {
      city_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Visits" field.</summary>
  public const int VisitsFieldNumber = 3;
  private int visits_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Visits {
    get { return visits_; }
    set {
      visits_ = value;
    }
  }

  /// <summary>Field number for the "Salary" field.</summary>
  public const int SalaryFieldNumber = 4;
  private double salary_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public double Salary {
    get { return salary_; }
    set {
      salary_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Customer);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Customer other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (City != other.City) return false;
    if (Visits != other.Visits) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Salary, other.Salary)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (City.Length != 0) hash ^= City.GetHashCode();
    if (Visits != 0) hash ^= Visits.GetHashCode();
    if (Salary != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Salary);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (City.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(City);
    }
    if (Visits != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Visits);
    }
    if (Salary != 0D) {
      output.WriteRawTag(33);
      output.WriteDouble(Salary);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (City.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(City);
    }
    if (Visits != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Visits);
    }
    if (Salary != 0D) {
      output.WriteRawTag(33);
      output.WriteDouble(Salary);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (City.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(City);
    }
    if (Visits != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Visits);
    }
    if (Salary != 0D) {
      size += 1 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Customer other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.City.Length != 0) {
      City = other.City;
    }
    if (other.Visits != 0) {
      Visits = other.Visits;
    }
    if (other.Salary != 0D) {
      Salary = other.Salary;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          City = input.ReadString();
          break;
        }
        case 24: {
          Visits = input.ReadInt32();
          break;
        }
        case 33: {
          Salary = input.ReadDouble();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          City = input.ReadString();
          break;
        }
        case 24: {
          Visits = input.ReadInt32();
          break;
        }
        case 33: {
          Salary = input.ReadDouble();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
